---
name: Validate

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  COLUMNS: 120

jobs:
  validate-butane:
    runs-on: ubuntu-latest
    env:
      BUTANE_VERSION: v0.21.0
    steps:
      - uses: actions/checkout@v4

      - name: Download Butane Transpiler
        run: >-
          gh release download
          ${{ env.BUTANE_VERSION }}
          --repo coreos/butane
          --pattern butane-x86_64-unknown-linux-gnu
          --output butane
        env:
          GH_TOKEN: ${{ github.token }}

      - run: chmod +x butane

      - name: Validate Butane Configuration
        run: ./butane --files-dir . --check --strict butane.yml
  validate-justfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - run: just --check --fmt
        env:
          JUST_UNSTABLE: true
